# Generated by Django 4.0.3 on 2022-04-29 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gum', '0008_rename_imege_createpost_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catigory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='createpost',
            options={'ordering': ['id'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddField(
            model_name='createpost',
            name='catigory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gum.catigory'),
        ),
    ]
