# Generated by Django 4.0.3 on 2022-04-29 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gum', '0009_catigory_alter_createpost_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catigory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='createpost',
            old_name='catigory',
            new_name='category',
        ),
    ]
