# Generated by Django 4.0.3 on 2022-05-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gum', '0011_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='createpost',
            options={'ordering': ['-id'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='category', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='createpost',
            name='author',
            field=models.CharField(max_length=30, verbose_name='Авторы'),
        ),
        migrations.AlterField(
            model_name='createpost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='createpost',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_img', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='createpost',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='createpost',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='createusers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='createusers',
            name='mail',
            field=models.EmailField(max_length=255, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='createusers',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='createusers',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Пароль'),
        ),
    ]
