# Generated by Django 4.0.3 on 2022-05-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gum', '0012_alter_category_options_alter_createpost_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createusers',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
