# Generated by Django 4.0.3 on 2022-05-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gum', '0013_createusers_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createusers',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата регистрации'),
        ),
    ]
